// <auto-generated />
using System;
using CorporateRiskManagementSystemBack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CorporateRiskManagementSystemBack.Migrations
{
    [DbContext(typeof(RiskDbContext))]
    [Migration("20251020170928_AddPdfReportToAuditReport")]
    partial class AddPdfReportToAuditReport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.AuditReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<byte[]>("PdfReport")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_report");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("ReportId")
                        .HasName("audit_reports_pkey");

                    b.HasIndex(new[] { "AuthorId" }, "idx_audit_author");

                    b.HasIndex(new[] { "DepartmentId" }, "idx_audit_department");

                    b.ToTable("audit_reports", "corp_risk_management");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("DepartmentId");

                    b.HasIndex(new[] { "Name" }, "departments_name_key")
                        .IsUnique();

                    b.ToTable("departments", "corp_risk_management");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.Risk", b =>
                {
                    b.Property<int>("RiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("risk_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RiskId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Likelihood")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("likelihood");

                    b.Property<int>("RiskType")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("RiskId");

                    b.HasIndex(new[] { "CreatedById" }, "idx_risks_created_by");

                    b.ToTable("risks", "corp_risk_management");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.RiskAssessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assessment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssessmentId"));

                    b.Property<int>("AssessedById")
                        .HasColumnType("integer")
                        .HasColumnName("assessed_by_id");

                    b.Property<DateTime>("AssessmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessment_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<short?>("ImpactScore")
                        .HasColumnType("smallint")
                        .HasColumnName("impact_score");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short?>("ProbabilityScore")
                        .HasColumnType("smallint")
                        .HasColumnName("probability_score");

                    b.Property<int>("RiskId")
                        .HasColumnType("integer")
                        .HasColumnName("risk_id");

                    b.HasKey("AssessmentId")
                        .HasName("risk_assessments_pkey");

                    b.HasIndex(new[] { "RiskId" }, "idx_assessment_risk");

                    b.HasIndex(new[] { "AssessedById" }, "idx_assessment_user");

                    b.ToTable("risk_assessments", "corp_risk_management");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", "corp_risk_management");
                });

            modelBuilder.Entity("RiskDepartment", b =>
                {
                    b.Property<int>("RiskId")
                        .HasColumnType("integer")
                        .HasColumnName("risk_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.HasKey("RiskId", "DepartmentId")
                        .HasName("risk_departments_pkey");

                    b.HasIndex("DepartmentId");

                    b.ToTable("risk_departments", "corp_risk_management");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.AuditReport", b =>
                {
                    b.HasOne("CorporateRiskManagementSystemBack.Domain.Entites.User", "Author")
                        .WithMany("AuditReports")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("audit_reports_author_id_fkey");

                    b.HasOne("CorporateRiskManagementSystemBack.Domain.Entites.Department", "Department")
                        .WithMany("AuditReports")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("audit_reports_department_id_fkey");

                    b.Navigation("Author");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.Risk", b =>
                {
                    b.HasOne("CorporateRiskManagementSystemBack.Domain.Entites.User", "CreatedBy")
                        .WithMany("Risks")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("risks_created_by_id_fkey");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.RiskAssessment", b =>
                {
                    b.HasOne("CorporateRiskManagementSystemBack.Domain.Entites.User", "AssessedBy")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("risk_assessments_assessed_by_id_fkey");

                    b.HasOne("CorporateRiskManagementSystemBack.Domain.Entites.Risk", "Risk")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("risk_assessments_risk_id_fkey");

                    b.Navigation("AssessedBy");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("RiskDepartment", b =>
                {
                    b.HasOne("CorporateRiskManagementSystemBack.Domain.Entites.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("risk_departments_department_id_fkey");

                    b.HasOne("CorporateRiskManagementSystemBack.Domain.Entites.Risk", null)
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("risk_departments_risk_id_fkey");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.Department", b =>
                {
                    b.Navigation("AuditReports");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.Risk", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("CorporateRiskManagementSystemBack.Domain.Entites.User", b =>
                {
                    b.Navigation("AuditReports");

                    b.Navigation("RiskAssessments");

                    b.Navigation("Risks");
                });
#pragma warning restore 612, 618
        }
    }
}
